### ISSUE TITLE
配置文件问题 给后来人参考

### ISSUE THREAD

**Issue by shijingyu** [Aliang-code/automatic-theater-jellyfin#2]
1.name参数识别不出来  需要给注释掉了
`The Compose file './docker-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'`
2.homarr的密码变量没设置   可以不设置 可以忽略
`WARNING: The HOMARR_PASSWORD variable is not set. Defaulting to a blank string.`
3.群晖1900端口被占用 改了其他端口
`ERROR: for jellyfin  Cannot start service jellyfin: driver failed programming external connectivity on endpoint jellyfin (1bfb8b15df9602314a1bcf62db936ffb8d14d2a1541af8e0c9559ba55d812d3d): Error starting userland proxy: listen udp4 0.0.0.0:1900: bind: address already in use`
4.homarr报错 需要创建icons文件夹
`automatic-theater-jellyfin/config/homarr/icons' does not exists`
5.transmission报错 需要手动创建一下watch文件夹
`ERROR: for transmission  Cannot start service transmission: Bind mount failed: '/video/watch' does not exists`
6.jellyfin报错 需要创建一下证书路径
`ERROR: for jellyfin  Cannot start service jellyfin: Bind mount failed: '/etc/letsencrypt/live' does not exists`

**Comment by shijingyu** [comment]
参考

**Comment by blueemp** [comment]
感谢，有帮助！
